### ISSUE TITLE
[http-handler] Handle repeated namespace permission headers

### ISSUE THREAD

**Issue by mecampbellsoup** [aanthonyrizzo/kubeapps#5]
Currently we use [`Header.Get`](https://pkg.go.dev/net/http@go1.18.1#Header.Get) when [extracting permissions from the request header](https://github.com/coreweave/kubeapps/blob/8666284d43c5f403827c6e9874602e100227a6ef/pkg/http-handler/http-handler.go#L94) because it was never expected to be more than a single occurrence of the header key `x-consumer-permissions`.

However, we are changing the format of this permissions header and need either of the following to be supported:

```
x-consumer-permissions: foo
x-consumer-permissions: bar
```
```
x-consumer-permissions: foo,bar
```
The `http-handler` code reference in this issue should be amended to use [`Header.Values`](https://pkg.go.dev/net/http@go1.18.1#Header.Values) instead of `Header.Get`.

cc @kriscode1

**Comment by mecampbellsoup** [comment]
@aanthonyrizzo I expect the upstream maintainers would welcome this change since it will be backwards compatible but we should probably open an issue there as well?

**Comment by goock** [comment]
Likely we want to support the following format:
```
x-consumer-permissions: foo,bar
x-consumer-permissions: foo1,bar1
```
Matt, you are right `Get` only 'Get gets the first value associated with the given key. ', whereas `Values` 'Values returns all values associated with the given key.'

**Comment by aanthonyrizzo** [comment]
Yes we def will want to PR it upstream, probably a welcomed change. One thing to note though. We currently run [version 2.4.2 for all of the backend and external services](https://github.com/coreweave/k8s-services/blob/master/all-sites/kubeapps/values.yaml) and we cant upgrade until I patch the regression. Not sure if we want to run a fork of 2.4.2 to get this out faster and then PR upstream for the latest version.

**Comment by mecampbellsoup** [comment]
Closing this for now as we are just going to have the gateway set a [single, comma-separated string containing all the header values](https://github.com/coreweave/api-gateway/blob/a9dc97694c4e045eeb205b208ac063eae193924c/auth.lua#L110).
